package school.sptech.Alem_da_Rota.destino;

import jakarta.annotation.PostConstruct;
import jakarta.validation.Valid;
import org.springframework.http.ResponseEntity;
import org.springframework.jdbc.core.BeanPropertyRowMapper;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.support.GeneratedKeyHolder;
import org.springframework.jdbc.support.KeyHolder;
import org.springframework.web.bind.annotation.*;

import java.sql.PreparedStatement;
import java.sql.Statement;
import java.util.List;

@RestController
@RequestMapping("/api/destinos")
@CrossOrigin(origins = {"http://localhost:5173", "http://127.0.0.1:5173"})
public class DestinoController {

    private final JdbcTemplate jdbcTemplate;

    // O Spring entrega o JdbcTemplate pronto por meio do construtor.
    public DestinoController(JdbcTemplate jdbcTemplate) {
        this.jdbcTemplate = jdbcTemplate;
    }

    // Cria a tabela no H2 quando a API é iniciada.
    @PostConstruct
    public void criarTabela() {
        String sql = """
                CREATE TABLE IF NOT EXISTS destino (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    nome VARCHAR(100) NOT NULL,
                    cidade VARCHAR(80) NOT NULL,
                    estado VARCHAR(2) NOT NULL,
                    categoria VARCHAR(100) NOT NULL,
                    melhor_epoca VARCHAR(100) NOT NULL,
                    valor_medio DECIMAL(12, 2) NOT NULL,
                    descricao VARCHAR(500) NOT NULL
                )
                """;

        jdbcTemplate.execute(sql);
    }

    @GetMapping
    public ResponseEntity<List<Destino>> listar() {
        String sql = "SELECT * FROM destino ORDER BY id";

        List<Destino> destinos = jdbcTemplate.query(
                sql,
                new BeanPropertyRowMapper<>(Destino.class)
        );

        return ResponseEntity.status(200).body(destinos);
    }

    @PostMapping
    public ResponseEntity<Destino> cadastrar(@Valid @RequestBody Destino destino) {
        destino.setId(null);
        destino.setEstado(destino.getEstado().trim().toUpperCase());

        String sql = """
                INSERT INTO destino
                (nome, cidade, estado, categoria, melhor_epoca, valor_medio, descricao)
                VALUES (?, ?, ?, ?, ?, ?, ?)
                """;

        KeyHolder keyHolder = new GeneratedKeyHolder();

        jdbcTemplate.update(conexao -> {
            PreparedStatement comando = conexao.prepareStatement(
                    sql,
                    Statement.RETURN_GENERATED_KEYS
            );

            comando.setString(1, destino.getNome());
            comando.setString(2, destino.getCidade());
            comando.setString(3, destino.getEstado());
            comando.setString(4, destino.getCategoria());
            comando.setString(5, destino.getMelhorEpoca());
            comando.setBigDecimal(6, destino.getValorMedio());
            comando.setString(7, destino.getDescricao());

            return comando;
        }, keyHolder);

        Long idGerado = keyHolder.getKeyAs(Long.class);
        destino.setId(idGerado);

        return ResponseEntity.status(201).body(destino);
    }
}
